// Code generated by tygo. DO NOT EDIT.

//////////
// source: client.go

/**
 * Client handles communication with the Hellenic Ministry API.
 */
export interface Client {
  BaseURL: string;
  HTTPClient?: any /* http.Client */;
}

//////////
// source: types.go

/**
 * HUnit represents a single Health Unit returned by the /rv/searchhunits endpoint.
 */
export interface HUnit {
  hunitId: any;
  hunit?: number /* int */;
  hunittype?: number /* int */;
  name: string;
  city: string;
  zip: string;
  phone1: string;
  phone2: string;
  address: string;
  lattitude: number /* float64 */;
  longitude: number /* float64 */;
  foreasId: number /* int */;
  region?: number /* int */;
  prefecture?: number /* int */;
  isactive?: number /* int */;
  clinics: any[];
  responseCode: number /* int */;
}
/**
 * Specialty represents a medical specialty metadata.
 */
export interface Specialty {
  speciality: number /* int */;
  name: string;
}
/**
 * Slot represents an available appointment time.
 */
export interface Slot {
  startTime: string;
  endTime: string;
  isFree: boolean;
}
/**
 * DaySlots represents a day's worth of slots for a unit.
 */
export interface DaySlots {
  date: string;
  slots: Slot[];
}
/**
 * SearchPayload represents the outgoing JSON body for searches and availability.
 */
export interface SearchPayload {
  startDate: string;
  endDate: string;
  prefectureID?: number /* int */;
  specialityID: number /* int */;
  foreasID: number /* int */;
  hunit?: number /* int */;
  cDoorId?: number /* int */;
  isCovid: number /* int */;
  isOnlyFd: number /* int */;
  isMachine: number /* int */;
}
/**
 * SlotsInitPayload represents the request body for /rv/getslotsinit.
 */
export interface SlotsInitPayload {
  startDate: string;
  endDate: string;
  specialityID: number /* int */;
  prefectureID?: number /* int */;
  hunit?: number /* int */;
  foreasID: number /* int */;
  isCovid: number /* int */;
  isOnlyFd: number /* int */;
  isMachine: number /* int */;
}
/**
 * SlotGroup represents a capacity block (e.g., 3 hours) in the /rv/getslotsinit response.
 */
export interface SlotGroup {
  groupColor: string;
  groupTitle: string;
  responseCode: number /* int */;
}
