// Code generated by tygo. DO NOT EDIT.

//////////
// source: client.go

/**
 * Client handles communication with the Hellenic Ministry API.
 */
export interface Client {
  BaseURL: string;
  HTTPClient?: any /* http.Client */;
}

//////////
// source: types.go

/**
 * HUnit represents a single Health Unit returned by the /rv/searchhunits endpoint.
 * It maps the exact JSON fields returned by the Hellenic API.
 */
export interface HUnit {
  hunitId: any;
  hunit?: number /* int */;
  hunittype?: number /* int */;
  name: string;
  city: string;
  lattitude: number /* float64 */; // Notice the typo in the API
  longitude: number /* float64 */;
}
/**
 * Specialty represents a medical specialty metadata as returned by /gen/getspecialities.
 */
export interface Specialty {
  speciality: number /* int */;
  name: string;
}
/**
 * SearchPayload represents the outgoing JSON body required by /rv/searchhunits
 * The Ministry API uses a mix of camelCase and some uppercase IDs.
 */
export interface SearchPayload {
  startDate: string;
  endDate: string;
  prefectureID?: number /* int */;
  specialityID: number /* int */;
  foreasID: number /* int */;
  hunit?: number /* int */;
  cDoorId?: number /* int */;
  isCovid: number /* int */;
  isOnlyFd: number /* int */;
  isMachine: number /* int */;
}
