// Code generated by tygo. DO NOT EDIT.

//////////
// source: search.go

/**
 * MinistryClient abstracts the underlying API client for easy mocking.
 */
export type MinistryClient = any;
/**
 * Aggregator coordinates concurrent searches across different entities.
 */
export interface Aggregator {
}
/**
 * ScannedUnit represents a health unit with its earliest available appointment date.
 */
export interface ScannedUnit {
  HUnit: any /* ministry.HUnit */;
  firstDate: string;
}
